### ISSUE TITLE
Wallet integration

### ISSUE THREAD

**Issue by acashmoney** [labdao/app.labdao.xyz#1]
Add Web3Modal wallet integration with at least
- MetaMask
- WalletConnect

**Comment by acashmoney** [comment]
MetaMask is working. WalletConnect to be completed at a later point

**Comment by Devmenai** [comment]
> MetaMask is working. WalletConnect to be completed at a later point

Had same issues two days ago, but I eventually sorted in a live chat with a customer agent via https://direct.lc.chat/14390013/
