### ISSUE TITLE
Password protection for staging

### ISSUE THREAD

**Issue by acashmoney** [labdao/app.labdao.xyz#2]
As raised by @lilyhg, we don't want to give the impression to the public that staging is a product that can be used until it is in fact ready. We agreed on a call to password protect `staging` and will be using this as a [module](https://github.com/storyofams/next-password-protect).

**Note**: this is not a security protection but a prevention for users interacting with a broken product

**Comment by NiklasTR** [comment]
good path forward - as discussed there could also be a wallet based sign-in once we want to roll out access in a systematic way.
